openapi: "3.0.3"
info:
  title: onecx-announcement-bff
  description: Backend-For-Frontend (BFF) service for onecx-announcement. This API provides endpoints to manage Announcements
  version: "1.0"
servers:
  - url: https://onecx-announcement-bff:8080
tags:
  - name: announcementInternal
    description: Managing Announcements
paths:
  /announcements/search:
    post:
      x-onecx:
        permissions:
          announcement:
            - read
      tags:
        - announcementInternal
      description: Search for announcements by search criteria
      operationId: searchAnnouncements
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnnouncementSearchCriteria'
      responses:
        "200":
          description: Announcement search results retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnnouncementPageResult'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /announcements/banner/search:
    post:
      x-onecx:
        permissions:
          announcement:
            - read
      tags:
        - announcementInternal
      description: Search for announcement banners by criteria
      operationId: searchAnnouncementBanners
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnnouncementBannerSearchCriteria'
      responses:
        "200":
          description: Announcements retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnnouncementPageResult'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /announcements/active/search:
    post:
      x-onecx:
        permissions:
          announcement:
            - read
      tags:
        - announcementInternal
      description: Search for active announcements by criteria
      operationId: searchActiveAnnouncements
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActiveAnnouncementsSearchCriteria'
      responses:
        "200":
          description: Active announcements retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActiveAnnouncementsPageResult'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /announcements:
    post:
      x-onecx:
        permissions:
          announcement:
            - write
      tags:
        - announcementInternal
      description: Create a new announcement
      operationId: createAnnouncement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAnnouncementRequest'
      responses:
        "201":
          description: Announcement created successfully
          headers:
            Location:
              required: true
              schema:
                type: string
                format: url
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Announcement'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /announcements/assignments:
    get:
      x-onecx:
        permissions:
          announcement:
            - read
      tags:
        - announcementInternal
      description: Get all product and workspace names to which announcements are assigned
      operationId: getAllAnnouncementAssignments
      responses:
        "200":
          description: Announcement assignments retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnnouncementAssignments'
  /announcements/{id}:
    get:
      x-onecx:
        permissions:
          announcement:
            - read
      tags:
        - announcementInternal
      description: Get an announcement by its id
      operationId: getAnnouncementById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Announcement retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Announcement'
    delete:
      x-onecx:
        permissions:
          announcement:
            - delete
      tags:
        - announcementInternal
      description: Delete an announcement by its id
      operationId: deleteAnnouncementById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Announcement deleted successfully
    put:
      x-onecx:
        permissions:
          announcement:
            - write
      tags:
        - announcementInternal
      description: Update an announcement by its id
      operationId: updateAnnouncementById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAnnouncementRequest'
      responses:
        "200":
          description: Announcement updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Announcement'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
components:
  schemas:
    AnnouncementAssignments:
      type: object
      properties:
        productNames:
          type: array
          items:
            type: string
        workspaceNames:
          type: array
          items:
            type: string
    CreateAnnouncementRequest:
      type: object
      required:
        - title
        - startDate
      properties:
        title:
          type: string
        content:
          type: string
        type:
          $ref: '#/components/schemas/AnnouncementType'
        priority:
          $ref: '#/components/schemas/AnnouncementPriorityType'
        status:
          $ref: '#/components/schemas/AnnouncementStatus'
        appearance:
          $ref: '#/components/schemas/AnnouncementAppearance'
        startDate:
          $ref: '#/components/schemas/OffsetDateTime'
        endDate:
          $ref: '#/components/schemas/OffsetDateTime'
        productName:
          type: string
        workspaceName:
          type: string
    AnnouncementSearchCriteria:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        type:
          $ref: '#/components/schemas/AnnouncementType'
        priority:
          $ref: '#/components/schemas/AnnouncementPriorityType'
        status:
          $ref: '#/components/schemas/AnnouncementStatus'
        appearance:
          type: array
          items:
            $ref: '#/components/schemas/AnnouncementAppearance'
        startDateFrom:
          $ref: '#/components/schemas/OffsetDateTime'
        startDateTo:
          $ref: '#/components/schemas/OffsetDateTime'
        endDateFrom:
          $ref: '#/components/schemas/OffsetDateTime'
        endDateTo:
          $ref: '#/components/schemas/OffsetDateTime'
        productName:
          type: string
        workspaceName:
          type: string
        pageNumber:
          format: int32
          description: The number of page.
          default: 0
          type: integer
        pageSize:
          format: int32
          description: The size of page
          default: 100
          maximum: 1000
          type: integer
    AnnouncementBannerSearchCriteria:
      type: object
      required:
        - currentDate
      properties:
        currentDate:
          $ref: '#/components/schemas/OffsetDateTime'
        productName:
          type: string
        workspaceName:
          type: string
        appearance:
          type: array
          items:
            $ref: '#/components/schemas/AnnouncementAppearance'
        pageNumber:
          format: int32
          description: The number of page.
          default: 0
          type: integer
        pageSize:
          format: int32
          description: The size of page
          default: 100
          maximum: 1000
          type: integer
    UpdateAnnouncementRequest:
      type: object
      required:
        - title
        - startDate
        - modificationCount
      properties:
        modificationCount:
          format: int32
          type: integer
        title:
          type: string
        content:
          type: string
        type:
          $ref: '#/components/schemas/AnnouncementType'
        priority:
          $ref: '#/components/schemas/AnnouncementPriorityType'
        status:
          $ref: '#/components/schemas/AnnouncementStatus'
        appearance:
          $ref: '#/components/schemas/AnnouncementAppearance'
        startDate:
          $ref: '#/components/schemas/OffsetDateTime'
        endDate:
          $ref: '#/components/schemas/OffsetDateTime'
        productName:
          type: string
        workspaceName:
          type: string
    Announcement:
      type: object
      properties:
        modificationCount:
          format: int32
          type: integer
        creationDate:
          $ref: '#/components/schemas/OffsetDateTime'
        creationUser:
          type: string
        modificationDate:
          $ref: '#/components/schemas/OffsetDateTime'
        modificationUser:
          type: string
        id:
          type: string
        title:
          type: string
        content:
          type: string
        type:
          $ref: '#/components/schemas/AnnouncementType'
        priority:
          $ref: '#/components/schemas/AnnouncementPriorityType'
        status:
          $ref: '#/components/schemas/AnnouncementStatus'
        appearance:
          $ref: '#/components/schemas/AnnouncementAppearance'
        startDate:
          $ref: '#/components/schemas/OffsetDateTime'
        endDate:
          $ref: '#/components/schemas/OffsetDateTime'
        productName:
          type: string
        workspaceName:
          type: string
    AnnouncementPageResult:
      type: object
      properties:
        totalElements:
          format: int64
          description: The total elements in the resource.
          type: integer
        number:
          format: int32
          type: integer
        size:
          format: int32
          type: integer
        totalPages:
          format: int64
          type: integer
        stream:
          type: array
          items:
            $ref: '#/components/schemas/Announcement'
    ActiveAnnouncementsSearchCriteria:
      type: object
      required:
        - currentDate
      properties:
        currentDate:
          $ref: '#/components/schemas/OffsetDateTime'
        workspaceName:
          type: string
        productName:
          type: string
        appearance:
          type: array
          items:
            $ref: '#/components/schemas/AnnouncementAppearance'
        pageNumber:
          format: int32
          description: The number of page.
          default: 0
          type: integer
        pageSize:
          format: int32
          description: The size of page
          default: 100
          maximum: 1000
          type: integer
    ActiveAnnouncementsPageResult:
      type: object
      properties:
        totalElements:
          format: int64
          description: The total elements in the resource.
          type: integer
        number:
          format: int32
          type: integer
        size:
          format: int32
          type: integer
        totalPages:
          format: int64
          type: integer
        stream:
          type: array
          items:
            $ref: '#/components/schemas/AnnouncementAbstract'
    AnnouncementAbstract:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        content:
          type: string
        type:
          $ref: '#/components/schemas/AnnouncementType'
        priority:
          $ref: '#/components/schemas/AnnouncementPriorityType'
        appearance:
          $ref: '#/components/schemas/AnnouncementAppearance'
        workspaceName:
          type: string
        productName:
          type: string
    AnnouncementPriorityType:
      enum:
        - IMPORTANT
        - NORMAL
        - LOW
      type: string
    AnnouncementStatus:
      enum:
        - ACTIVE
        - INACTIVE
      type: string
    AnnouncementType:
      enum:
        - EVENT
        - INFO
        - SYSTEM_MAINTENANCE
      type: string
    AnnouncementAppearance:
      enum:
        - BANNER
        - WELCOME
        - ALL
      type: string
    OffsetDateTime:
      format: date-time
      type: string
      example: 2022-03-10T12:15:50-04:00
    ProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailInvalidParam'
    ProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string
